[build]
builder = "dockerfile"
dockerfile = "./Dockerfile"

[deploy]
startCommand = "node --max-old-space-size=512 --expose-gc server.js"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000"
